


jest.mock('', () => {
    useLoginInMutation: jest.fn()
    useRegisterUserMutation: jest.fn()
    useGetMeMutation: jest.fn()
    useChangePasswordMutation: jest.fn()
    useChangeNameAndCardMutation: jest.fn()
    useCodeForEmailMutation: jest.fn()
    useChangeEmailMutation: jest.fn()
    useCallMutation: jest.fn()
    useChangePhoneMutation: jest.fn()
    useChangePasswordInProfileMutation: jest.fn()
    useCreateCategoryMutation: jest.fn()
    useGetCategoriesMutation: jest.fn()
    useUpdateCategoryMutation: jest.fn()
    useDeleteCategoryMutation: jest.fn()
    useCallCodeMutation: jest.fn()
    useAddGroupMutation: jest.fn()
    useGetGroupsMutation: jest.fn()
    useDeleteGroupMutation: jest.fn()
    useUpdateGroupMutation: jest.fn()
    useCreateAndCheckAllPostsMutation: jest.fn()
    useGetAllPostsMutation: jest.fn()
    useStartAddTutorsPostsMutation: jest.fn()
    useDeleteAllPostsFromMainRepositoryMutation: jest.fn()
    useAddNewFileMutation: jest.fn()
    useGetFilesMutation: jest.fn()
    useDeleteFileMutation: jest.fn()
    useDeleteGroupInMainRepositoryMutation: jest.fn()
    useGetLogsMutation: jest.fn()
    useAddNewPriceBlockMutation: jest.fn()
    useGetAllPricesMutation: jest.fn()
    useGetFreePeriodMutation: jest.fn()
    useAddChatMutation: jest.fn()
    useGetChatMutation: jest.fn()
    useGetAllKeysRedisMutation: jest.fn()
    useGetPostsRedisMutation: jest.fn()
    useUpdatePriceMutation: jest.fn()
    useSendMassageMutation: jest.fn()
    usePaymentMutation: jest.fn()
    useVerifyTgMutation: jest.fn()
    useActivateTgMutation: jest.fn()
    useGetPhoneCodeTgMutation: jest.fn()
    useActivateTgProfileMutation: jest.fn()
    useGiveInfoMutation: jest.fn()
    useNumberTgForgetPasswordMutation: jest.fn()
})


describe('тестируем асинхронные запросы', () => {

})